version: "3.4"

services:
  mongodb:
    image: mongo:latest
    container_name: "data7-mongo"
    hostname: mongodb
    volumes:
      - ./conf/mongodb/mongod.conf:/etc/mongod.conf
      - ./conf/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./storage/mongodb/data/db/:/data/db/
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: data7
      MONGO_INITDB_USERNAME: data7
      MONGO_INITDB_PASSWORD: data7
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "27017:27017"
    command: ["-f", "/etc/mongod.conf"]
