[tool.poetry]
name = "pydata7"
version = "0.1.0"
description = ""
authors = ["Pereira Fabio <fabio.pereira.002@student.uni.lu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
